### PR TITLE
feat: Update Rx to last version

### PR DESCRIPTION
**Pull request by tebeco**

### CODE REVIEW

**Comment by alexvictoor** [comment]
Thanks horse guy for this PR
I will take care of this one asap, probably this week

**Comment by tebeco** [comment]
We're blocked because of Transitive Dependency in lots of repository without this one

**Comment by alexvictoor** [comment]
I will publish a new version to nuget shortly

**Comment by tebeco** [comment]
Perfect,

Beware of your versionning, seems that you have 4 digit.
Known versions :

```
>paket find-package-versions nuget MarbleTest.Net
Paket version 4.3.0
1.1.1.0
1.1.0.0
1.0.0.0
13 seconds - ready.
```

**Pull request merged**
